/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery  Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func (s *Server) getNFDiscoveryRoutes() []Route {
	return []Route{
		{
			Method:  http.MethodGet,
			Pattern: "/",
			APIFunc: func(ctx *gin.Context) {
				ctx.JSON(http.StatusOK, gin.H{"status": "Hello World!"})
			},
		},
		{
			Method:  http.MethodPost,
			Pattern: "/nf-instances",
			APIFunc: s.getSearchNFInstances,
		},
	}
}

// SearchNFInstances - Search a collection of NF Instances
func (s *Server) getSearchNFInstances(c *gin.Context) {
	auth_err := authorizationCheck(c, "nnrf-disc")
	if auth_err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": auth_err.Error()})
		return
	}

	query := c.Request.URL.Query()
	s.Processor().NFDiscoveryProcedure(c, query)
}
